config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navibar">
     <%= link_to 'breweries', breweries_path %>
     <%= link_to 'beers', beers_path %>
     <%= link_to 'ratings', ratings_path %>
     <%= link_to 'users', users_path %>
     <%= link_to 'beer clubs', beer_clubs_path %>
     |
  
     <% if current_user %>
        <%= link_to 'Rate a beer', new_rating_path %>
        <%= link_to 'Join a club', new_membership_path %>
     |
        <%= link_to current_user.username, current_user %>
        <%= link_to 'Sign out', session_path, 
         data: {
          "turbo-method": :delete
          }, class: "link-secondary smooth"  %>
     <% else %>
        <%= link_to 'Sign up', new_user_path %>
        <%= link_to 'Sign in', signin_path %>
     <% end %>
    </div>
    <%= yield %>
  </body>
</html>